[package]
name = "sopipe"
version = "0.1.0"
authors = ["Shiwei Zhang <ylxdzsw@gmail.com>"]
edition = "2018"

[profile.release]
lto = true
panic = 'abort'

[dependencies]
oh-my-rust = { git = "https://github.com/ylxdzsw/oh-my-rust" }
tokio = { version = "0.3", features = ["rt", "rt-multi-thread", "io-util", "io-std", "net", "time", "process", "macros", "sync", "stream", "signal", "fs"] }
futures = "0.3"
libloading = "0.5"

[workspace]
members = [
    "plugins/socks5"
]
