[package]
name = "sopipe"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.12", features = ["rt", "rt-multi-thread", "sync", "time", "signal"] } # "io-util", "io-std", "net", "process", "fs"
pest = "2.0"
pest_derive = "2.0"

api = { path = "api" }

socks5 = { path = "components/socks5", optional = true }
stdio = { path = "components/stdio", optional = true }
tcp = { path = "components/tcp", optional = true }
xor = { path = "components/xor", optional = true }

[features]
# core includes most endpoints. It serves as the basis for "slim" builds.
core = ["tcp", "stdio"]

# default includes most common components that supports static linking.
default = ["core", "xor"]

[workspace]
