[package]
name = "sopipe"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.12", features = ["rt", "rt-multi-thread", "sync", "time", "signal"] } # "io-util", "io-std", "net", "time", "process", "fs"
pest = "2.0"
pest_derive = "2.0"

api = { path = "api" }

socks5 = { path = "components/socks5", optional = true }
stdio = { path = "components/stdio", optional = true }
tcp = { path = "components/tcp", optional = true }
xor = { path = "components/xor", optional = true }

[features]
core = ["tcp", "stdio"] # core includes endpoints components. A core-only build is a socat clone without middlewares. It serves as the basis for a "slim" build.
default = ["core", "xor"] # default includes most common components. We select components such that a default build can be statically linked and <= 4MB after stripping.

[workspace]
