[package]
name = "xor"
version = "0.1.0"
edition = "2021"

[dependencies]
api = { path = "../../api" }
oh-my-rust = { git = "https://github.com/ylxdzsw/oh-my-rust" }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
