[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.12", features = ["rt", "rt-multi-thread", "io-util", "io-std", "net", "time", "process", "sync", "signal", "fs"] }
serde = "1.0"
async-trait = "0.1"
thiserror = "1.0"
