name: CI & Build
on: [push, pull_request]

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: x86_64-linux-gnu, os: ubuntu-latest, target: x86_64-unknown-linux-gnu }
          - { name: x86_64-linux-musl, os: ubuntu-latest, target: x86_64-unknown-linux-musl }
          - { name: x86_64-darwin, os: macos-latest, target: x86_64-apple-darwin }
          - { name: x86_64-windows-msvc, os: windows-latest, target: x86_64-pc-windows-msvc }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - run: sudo apt-get install musl-tools
        if: matrix.name == 'x86_64-linux-musl'
      - run: cargo test --all --target ${{ matrix.target }}
      - run: cargo build --release --target ${{ matrix.target }}
        env:
            RUSTFLAGS: -C target-feature=+crt-static
      - run: strip target/${{ matrix.target }}/release/sopipe
        if: matrix.name != 'x86_64-windows-msvc'
      - run: mv target/${{ matrix.target }}/release/sopipe.exe target/${{ matrix.target }}/release/sopipe
        if: matrix.name == 'x86_64-windows-msvc'
      - uses: actions/upload-artifact@v2
        with:
          name: sopipe-${{ matrix.name }}
          path: target/${{ matrix.target }}/release/sopipe
  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v2
      - run: |
          mkdir artifacts
          mv sopipe-x86_64-linux-gnu/sopipe artifacts/sopipe-x86_64-linux-gnu
          mv sopipe-x86_64-linux-musl/sopipe artifacts/sopipe-x86_64-linux-musl
          mv sopipe-x86_64-darwin/sopipe artifacts/sopipe-x86_64-darwin
          mv sopipe-x86_64-windows-msvc/sopipe artifacts/sopipe-x86_64-windows-msvc
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
